# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_extensions/',
                'doc_host': 'https://muellerzr.github.io',
                'git_url': 'https://github.com/muellerzr/nbdev-extensions/',
                'lib_path': 'nbdev_extensions'},
  'syms': { 'nbdev_extensions.mknb': { 'nbdev_extensions.mknb._mk_nb': ('mknb.html#_mk_nb', 'nbdev_extensions/mknb.py'),
                                       'nbdev_extensions.mknb.new_nb': ('mknb.html#new_nb', 'nbdev_extensions/mknb.py')}}}